# Netlify configuration file

# Build settings
[build]
  # Command to build the site
  command = "npm run build"
  # Directory to publish (the output of the build)
  publish = "dist"

# Functions settings
[functions]
  # Directory where serverless functions are located
  directory = "netlify/functions"

# Redirect rule for Single Page Applications (SPA)
# This ensures that client-side routing works correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200