[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Specify the Node.js version to use for the build, matching package.json
  NODE_VERSION = "20"

  [secrets]
  # Omit specific keys from scanning (if they're false positives)
  SECRETS_SCAN_OMIT_KEYS = "SOME_KEY,ANOTHER_KEY"
  
  # Omit specific paths from scanning
  SECRETS_SCAN_OMIT_PATHS = "public/config.json,src/test-data/*"

# Secrets scanning configuration to prevent build failures
[secrets_scanning]
  # A list of secret keys that should be ignored by the scanner.
  # This is necessary because our documentation files reference these keys by name.
  omit_keys = [
    "API_KEY",
    "AIRTABLE_API_KEY",
    "AIRTABLE_BASE_ID",
    "PROJECTS_TABLE_NAME",
    "PROSPECTS_TABLE_NAME",
    "VITE_FIREBASE_API_KEY",
    "VITE_FIREBASE_APP_ID",
    "VITE_FIREBASE_AUTH_DOMAIN",
    "VITE_FIREBASE_MESSAGING_SENDER_ID",
    "VITE_FIREBASE_PROJECT_ID",
    "VITE_FIREBASE_STORAGE_BUCKET"
  ]