[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Specify the Node.js version to use for the build, matching package.json
  NODE_VERSION = "20"

[secrets]
  # Omit specific keys from scanning
  SECRETS_SCAN_OMIT_KEYS = "AIRTABLE_API_KEY,AIRTABLE_BASE_ID,API_KEY,VITE_FIREBASE_API_KEY,VITE_FIREBASE_APP_ID,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET"
  
  # Omit build directory from scanning
  SECRETS_SCAN_OMIT_PATHS = "dist/*,build/*"