[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[secrets_scan]
  # This tells Netlify's scanner to ignore the public client-side Firebase keys.
  # The '*' is a wildcard that matches all variables starting with VITE_FIREBASE_.
  omit_keys = ["VITE_FIREBASE_*"]